// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCanqMInNsOHUxaKHlrFPbhg0p9bY2ezgQ',
    appId: '1:747086167586:android:9a8368a4ebc38e22a4147b',
    messagingSenderId: '747086167586',
    projectId: 'glide-30a3f',
    storageBucket: 'glide-30a3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmk5h2GlllxRpMBtL45lAWZs3pdSNszXA',
    appId: '1:747086167586:ios:ed13d8cd0f092352a4147b',
    messagingSenderId: '747086167586',
    projectId: 'glide-30a3f',
    storageBucket: 'glide-30a3f.firebasestorage.app',
    androidClientId: '747086167586-sb6dhhcvu0855t02g803qmh8obfe7udl.apps.googleusercontent.com',
    iosClientId: '747086167586-h1785jbauvpnv6fo29fqpjhhi8rgvpsv.apps.googleusercontent.com',
    iosBundleId: 'com.adamexpress.glide',
  );
}
